"""add new_user field

Revision ID: 2c102b2c9e09
Revises: 59562d551a1d
Create Date: 2026-06-21 22:36:19.002541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c102b2c9e09'
down_revision: Union[str, Sequence[str], None] = '59562d551a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Используем server_default
    op.add_column('user',
        sa.Column('new', sa.Boolean(),
                 nullable=False,
                 server_default='true')  # PostgreSQL создаст поле с DEFAULT
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'new')
    # ### end Alembic commands ###
