"""Fix column name is_activae to is_active

Revision ID: 457d9d81b992
Revises: 2c102b2c9e09
Create Date: 2026-06-27 17:04:00.845444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457d9d81b992'
down_revision: Union[str, Sequence[str], None] = '2c102b2c9e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'is_active')
    # ### end Alembic commands ###
