"""add gift and trial subscription

Revision ID: 62b9ddc20ec1
Revises: 694c85cf67ee
Create Date: 2026-05-09 20:47:00.163325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b9ddc20ec1'
down_revision: Union[str, Sequence[str], None] = '694c85cf67ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Добавляем с server_default
    op.add_column('subscription', 
        sa.Column('is_trial', sa.Boolean(), 
                  nullable=False, 
                  server_default='false'))  # <-- Вот это спасает
    
    op.add_column('subscription',
        sa.Column('is_gift', sa.Boolean(),
                  nullable=False,
                  server_default='false'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'is_gift')
    op.drop_column('subscription', 'is_trial')
    # ### end Alembic commands ###
