"""add is_activated column in promocode model

Revision ID: 66347637f498
Revises: 8757a50de3da
Create Date: 2026-07-18 16:31:38.183510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66347637f498'
down_revision: Union[str, Sequence[str], None] = '8757a50de3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocode', sa.Column('is_activated', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_promocode_is_activated'), 'promocode', ['is_activated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promocode_is_activated'), table_name='promocode')
    op.drop_column('promocode', 'is_activated')
    # ### end Alembic commands ###
