"""google only auth

Revision ID: 694c85cf67ee
Revises: 8583165c4bd6
Create Date: 2026-05-07 18:46:53.105527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694c85cf67ee'
down_revision: Union[str, Sequence[str], None] = '8583165c4bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=254),
               nullable=False)
    op.alter_column('user', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(op.f('uq_users_phone'), 'user', type_='unique')
    op.drop_constraint(op.f('user_password_hash_key'), 'user', type_='unique')
    op.create_unique_constraint('uq_users_google_id', 'user', ['google_id'])
    op.drop_column('user', 'phone')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint('uq_users_google_id', 'user', type_='unique')
    op.create_unique_constraint(op.f('user_password_hash_key'), 'user', ['password_hash'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_phone'), 'user', ['phone'], postgresql_nulls_not_distinct=False)
    op.alter_column('user', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=254),
               nullable=True)
    # ### end Alembic commands ###
