"""Update promocode model

Revision ID: af12421fe046
Revises: 6bbb042f8986
Create Date: 2026-07-03 13:53:58.402330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af12421fe046'
down_revision: Union[str, Sequence[str], None] = '6bbb042f8986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocode',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_disposable', sa.Boolean(), nullable=False),
    sa.Column('purpose', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promocode_code'), 'promocode', ['code'], unique=True)
    op.create_index(op.f('ix_promocode_id'), 'promocode', ['id'], unique=False)
    op.create_index(op.f('ix_promocode_is_active'), 'promocode', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promocode_is_active'), table_name='promocode')
    op.drop_index(op.f('ix_promocode_id'), table_name='promocode')
    op.drop_index(op.f('ix_promocode_code'), table_name='promocode')
    op.drop_table('promocode')
    # ### end Alembic commands ###
