"""add target ids

Revision ID: e2011b758f1f
Revises: d6bfa309cbe5
Create Date: 2026-07-16 17:36:57.391220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2011b758f1f'
down_revision: Union[str, Sequence[str], None] = 'd6bfa309cbe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocode', sa.Column('target_user_ids', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promocode', 'target_user_ids')
    # ### end Alembic commands ###
