MIN_PATH_SCHEME = 5
MAX_PATH_SCHEME = 150

MIN_DOMAIN_SCHEME = 5
MAX_DOMAIN_SCHEME = 150

MAX_COUNTRY_SCHEME = 150

EMAIL_MAX = 254
PHONE_MAX = 32
TG_ID_MAX = 64
USERNAME_MAX = 150
PASS_HASH_MAX = 255

CHECK_MAIL_FORMAT = (r"email IS NULL OR email ~ '^[a-zA-Z0-9]"
                     r"[a-zA-Z0-9._%+-]{0,63}@gmail\.com$'")
